// Initial Projects Master Dataset (Fallback & Default Seed Data)
window.DEFAULT_PROJECTS = [
  {
    id: "januarydelight",
    title: "January Delight — Serverless Ordering & Real-Time Sync Platform",
    category: "fullstack",
    cardType: "featured",
    badgeText: "LIVE PRODUCTION",
    badgeColor: "rgba(255,107,53,0.2)",
    badgeTextColor: "#ff6b35",
    previewImg: "preview_januarydelight.jpg",
    browserUrl: "januarydelight.com",
    liveUrl: "https://www.januarydelight.com/",
    githubUrl: "",
    tags: ["Node.js", "Cloudflare Workers", "REST APIs", "Vanilla JS"],
    desc: "Architected a serverless ordering platform using Node.js on Cloudflare Workers and RESTful APIs that maintained 99.9% uptime to process real-time customer orders with high availability. Constructed a real-time order pipeline with live admin panel synchronization (<500ms latency) and full security layers.",
    featured: true,
    order: 1
  },
  {
    id: "shikshaguard",
    title: "Shiksha Guard — AI Infrastructure Validator (Team Project)",
    category: "ai fullstack frontend",
    cardType: "side",
    badgeText: "AI SYSTEM",
    badgeColor: "rgba(76,201,240,0.2)",
    badgeTextColor: "#4cc9f0",
    previewImg: "preview_shikshaguard.jpg",
    browserUrl: "shikshaguard.onrender.com",
    liveUrl: "https://shikshaguard-frontend.onrender.com/",
    githubUrl: "",
    tags: ["React.js", "Node.js", "FastAPI", "India AI 2026"],
    desc: "Engineered frontend architecture and integrated REST APIs for a government-facing AI validation system under Samagra Shiksha, resulting in a live pitch to AiKosh officials. Recognized as a featured submission in the national India AI Innovation Challenge 2026.",
    featured: true,
    order: 2
  },
  {
    id: "meecrebit",
    title: "meeCrebit — Privacy-First Finance App",
    category: "ai frontend",
    cardType: "half",
    badgeText: "ON-DEVICE AI",
    badgeColor: "rgba(152,224,110,0.2)",
    badgeTextColor: "#98e06e",
    previewImg: "preview_meecrebit.jpg",
    browserUrl: "meecrebit.app",
    liveUrl: "",
    githubUrl: "https://github.com/Uttham68/meeCrebit",
    tags: ["Capacitor", "On-Device AI", "JavaScript"],
    desc: "Programmed a privacy-first cross-platform mobile web app with a custom on-device AI inference engine for confidential financial analytics and intelligent budgeting.",
    featured: false,
    order: 3
  },
  {
    id: "kinneraimages",
    title: "Kinnera Images | AI & Photography Studio",
    category: "frontend",
    cardType: "half",
    badgeText: "STUDIO",
    badgeColor: "rgba(124,58,237,0.2)",
    badgeTextColor: "#a37fe0",
    previewImg: "preview_kinneraimages.jpg",
    browserUrl: "kinneraimages.netlify.app",
    liveUrl: "https://kinneraimages.netlify.app/",
    githubUrl: "",
    tags: ["HTML5 / CSS3", "JavaScript", "Production"],
    desc: "Digital presence for Warangal's premier photography & AI studio featuring dynamic portfolio showcases, mobile-first design, and optimized Core Web Vitals.",
    featured: false,
    order: 4
  },
  {
    id: "bingehub",
    title: "BingeHub | Anime & TV Tracking Web Application",
    category: "frontend",
    cardType: "full",
    badgeText: "WEB APP",
    badgeColor: "rgba(255,209,102,0.2)",
    badgeTextColor: "#ffd166",
    previewImg: "preview_bingehub.jpg",
    browserUrl: "bingehubz.netlify.app",
    liveUrl: "https://bingehubz.netlify.app/",
    githubUrl: "",
    tags: ["HTML5", "CSS3", "JavaScript", "REST APIs"],
    desc: "Interactive tracker for television shows and anime with dynamic search, status filtering, responsive visual cards, and state persistence.",
    featured: false,
    order: 5
  }
];
